sonar.projectKey=psteixeira23_developer-joi-delivery-java
sonar.organization=psteixeira23
sonar.projectName=developer-joi-delivery-java
sonar.projectVersion=1.0.0
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Diretórios de código fonte e testes
sonar.sources=src/main/java
sonar.tests=src/test/java

# Compilação e relatórios
sonar.java.binaries=build/classes/java/main
sonar.junit.reportPaths=build/test-results/test
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
